version: '3.8'
services:
  redis-stack-server:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight UI
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
